{% set name = "prism-ds" %}
{% set version = "0.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/prism-ds-{{ version }}.tar.gz
  sha256: 97264b8c0be2746ee0c6391156e0730364509819e5baef266249e8b9ae11c9ec

build:
  entry_points:
    - prism = prism.main:invoke
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=41.1.0
    - pip
  run:
    - python >=3.7
    - astor >=0.7
    - boto3 >=1
    - botocore >=1
    - click >=8
    - networkx >=2
    - numpy >=1
    - pandas >=1
    - pyyaml >=6
    - requests >=2
    - jinja2 ==3.1.2
    - markupsafe >=2.0
    - coolname >=2.2
    - shortuuid >=1.0
    - rich-click >=1.6.1
    - pillow >=9.5.0

test:
  imports:
    - prism
  commands:
    - pip check
    - prism --help
  requires:
    - pip

about:
  home: https://www.runprism.com/
  dev_url: https://github.com/runprism/prism
  doc_url: https://docs.runprism.com/
  summary: The easiest way to create data pipelines in Python.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
